name: CI-SRM-Basic 
on:
  push:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-host
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: SRM Scan
        uses: synopsys-sig/synopsys-action@v1.13.0
        with:
          ### SCANNING: Required fields
          srm_url: ${{ secrets.SRM_URL }}
          srm_apikey: ${{ secrets.SRM_API_KEY }}
          srm_assessment_types: "SCA,SAST"      